server:
  port: 8080

stats-server:
  url: http://stats-server:9090

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm_main_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Moscow
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    root: INFO
    ru.practicum.ewm.main: DEBUG